services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: "Europe/Berlin"
      FTLCONF_dns_listeningMode: "ALL"
    volumes:
      - "./pihole/etc-pihole:/etc/pihole"
      - "./pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - lab_net

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./portainer/portainer_data:/data"
    restart: always
    networks:
      - lab_net

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    environment:
      DOCKER_API_VERSION: "1.40"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
    networks:
      - lab_net

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - lab_net

networks:
  lab_net:
    name: lab_net
    driver: bridge
